version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 9672:5672
      - 15672
  mongo:
    image: mongo:jessie
    ports: ["29017:27017"]
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
